apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: abs194h6f-python
  janus-idp.io/tekton: abs194h6f-python
  backstage.io/kubernetes-id: abs194h6f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: abs194h6f-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
